#!/usr/bin/env sh

getc_log() {
  echo "$*" >&2
}

getc_dependencies() {
  if [ ! -d "$1" ]; then
    return 127
  fi

  if [ ! -f "$1/dependencies.txt" ]; then
    return 0
  fi

  while read -r URL; do
    local DEP_DIR="$TARGET_DIR/$(echo "$URL" | sha256sum | head -c 10)"

    if [ "$3" = "pre" ]; then
      "$2" "$URL" "$DEP_DIR" || return 126
      getc_dependencies "$DEP_DIR" "$2" "$3" || return 125
    else
      getc_dependencies "$DEP_DIR" "$2" "$3" || return 124
      "$2" "$URL" "$DEP_DIR" || return 123
    fi
  done < "$1/dependencies.txt"
}

getc_foreach_dependency_pre() {
  getc_dependencies "$PWD" "$1" pre
}

getc_foreach_dependency_post() {
  getc_dependencies "$PWD" "$1" post
}

getc_setup_dependency() {
  [ ! -d "$2" ] && getc_fetch "$1" "$2"
}

getc_print_cxxflags() {
  make --quiet -f "$2/getc.mk" cxxflags
}

getc_print_ldflags() {
  make --quiet -f "$2/getc.mk" ldflags
}

getc_make() {
  getc_exec make --quiet -f "getc.mk"
}

getc_build() {
  (cd "$2" && getc_make)
}

getc_update() {
  getc_log "installing $1"
  git -C "$2" pull
}

getc_fetch() {
  getc_log "installing $1"
  git clone --depth 1 --single-branch -q "$1" "$2"
}

getc_cxxflags() {
  getc_foreach_dependency_pre getc_print_cxxflags | paste -s -d ' '
}

getc_ldflags() {
  getc_foreach_dependency_pre getc_print_ldflags | paste -s -d ' '
}

getc_exec() {
  LDFLAGS="$(getc_ldflags)" CXXFLAGS="$(getc_cxxflags)" $*
}

getc_install() {
  getc_foreach_dependency_pre getc_setup_dependency
  getc_foreach_dependency_post getc_build
}

getc() {
  TARGET_DIR="${TARGET_DIR-"$PWD/vendor"}"

  case "$1" in
    install )
      getc_install
      ;;

    exec )
      shift
      getc_exec $*
      ;;

    update )
      getc_foreach_dependency_pre getc_update
      ;;

    deps )
      getc_foreach_dependency_pre echo
      ;;

    make )
      getc_install
      getc_make
      ;;
  esac
}

getc $*
